"""
Monte Carlo Audit — Robustness & Stress Testing.
Runs any strategy through N "Alternative Timelines" generated by 
applying random perturbations (jitter, vol scaling, and macro lag) to 
historical data.
"""

import argparse
import concurrent.futures
import os
import random
import sys
import time

import numpy as np
import pandas as pd

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
sys.path.insert(0, os.path.dirname(__file__))

from utils import resolve_strategy
from src.tournament.runner import _execute_simulation
from src.helpers.data_provider import load_spy_data

def perturb_data(df: pd.DataFrame, jitter_std=0.0005, vol_scale_range=(0.9, 1.1), macro_shift_max=2):
    df_alt = df.copy()
    v_scale = random.uniform(*vol_scale_range)
    rets = df_alt['close'].pct_change().fillna(0)
    alt_rets = (rets * v_scale) + np.random.normal(0, jitter_std, len(rets))
    new_close = df_alt['close'].iloc[0] * (1 + alt_rets).cumprod()
    ratio = new_close / df_alt['close']
    df_alt['open'] *= ratio
    df_alt['high'] *= ratio
    df_alt['low'] *= ratio
    df_alt['close'] = new_close
    shift = random.randint(-macro_shift_max, macro_shift_max)
    if shift != 0:
        df_alt['vix'] = df_alt['vix'].shift(shift).ffill().bfill()
        df_alt['yield_curve'] = df_alt['yield_curve'].shift(shift).ffill().bfill()
    return df_alt

def run_single_simulation(strategy_type, strategy_kwargs, df_perturbed):
    price_data_list = df_perturbed[['open', 'high', 'low', 'close', 'volume', 'vix', 'yield_curve']].to_dict('records')
    dates = df_perturbed.index
    res = _execute_simulation(
        strategy_type=strategy_type,
        price_data_list=price_data_list,
        dates=dates,
        strategy_kwargs=strategy_kwargs
    )
    return res['metrics']

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Monte Carlo Audit — Robustness Stress Test")
    parser.add_argument("strategy", type=str, help="Path to genome JSON or Strategy Name")
    parser.add_argument("--iterations", type=int, default=50, help="Number of alternative timelines (default 50)")
    parser.add_argument("--jitter", type=float, default=0.0005, help="Daily return jitter (std dev)")
    parser.add_argument("--vol", type=float, default=0.1, help="Max volatility scaling (e.g. 0.1 = 0.9x to 1.1x)")
    parser.add_argument("--shift", type=int, default=2, help="Max macro signal shift (days)")
    args = parser.parse_args()

    try:
        strategy = resolve_strategy(args.strategy)
    except Exception as e:
        print(f"ERROR: {e}")
        sys.exit(1)

    print(f"\n[1/3] Loading historical template...")
    df_real = load_spy_data("1993-01-01")
    
    print(f"[2/3] Generating {args.iterations} alternative timelines and simulating for {strategy.NAME}...")
    
    strat_type = strategy.__class__
    strat_kwargs = {'genome': getattr(strategy, 'genome', None)} if hasattr(strategy, 'genome') else {}
    
    results = []
    start_time = time.time()
    
    max_workers = max(1, os.cpu_count() - 2)
    with concurrent.futures.ProcessPoolExecutor(max_workers=max_workers) as executor:
        futures = []
        for i in range(args.iterations):
            df_alt = perturb_data(
                df_real, 
                jitter_std=args.jitter, 
                vol_scale_range=(1.0 - args.vol, 1.0 + args.vol),
                macro_shift_max=args.shift
            )
            futures.append(executor.submit(run_single_simulation, strat_type, strat_kwargs, df_alt))
        
        for i, future in enumerate(concurrent.futures.as_completed(futures)):
            try:
                results.append(future.result())
                print(f"\r      Progress: {len(results)}/{args.iterations} simulations complete", end="", flush=True)
            except Exception as e:
                print(f"\n      ERROR in simulation {i}: {e}")

    elapsed = time.time() - start_time
    print(f"\n[3/3] Audit complete in {elapsed:.1f}s. Generating report...")
    
    cagrs = [m['cagr'] * 100 for m in results]
    dds = [m['max_dd'] * 100 for m in results]
    sharpes = [m['sharpe'] for m in results]
    
    avg_cagr, med_cagr = np.mean(cagrs), np.median(cagrs)
    avg_dd, med_dd, worst_dd = np.mean(dds), np.median(dds), np.min(dds)
    ruin_rate = sum(1 for d in dds if d < -80) / len(dds) * 100
    
    w = 70
    print("\n" + "=" * w)
    print(f"  MONTE CARLO AUDIT: {strategy.NAME}")
    print(f"  Iterations: {args.iterations}")
    print("=" * w)
    
    print(f"\n  {'METRIC':<20} | {'AVERAGE':>10} | {'MEDIAN':>10} | {'WORST':>10}")
    print(f"  {'-' * (w - 4)}")
    print(f"  {'CAGR':<20} | {avg_cagr:>9.2f}% | {med_cagr:>9.2f}% | {np.min(cagrs):>9.2f}%")
    print(f"  {'Max Drawdown':<20} | {avg_dd:>9.2f}% | {med_dd:>9.2f}% | {worst_dd:>9.2f}%")
    print(f"  {'Sharpe Ratio':<20} | {np.mean(sharpes):>10.2f} | {np.median(sharpes):>10.2f} | {np.min(sharpes):>10.2f}")
    
    print(f"\n  {'STRESS TEST RESULTS':-<{w-4}}")
    ruin_color = "!!!" if ruin_rate > 10 else "OK"
    print(f"  Probability of Ruin (>80% DD):   {ruin_rate:>6.1f}%  [{ruin_color}]")
    low_cagr_rate = sum(1 for c in cagrs if c < 15) / len(cagrs) * 100
    print(f"  Probability of Underperformance: {low_cagr_rate:>6.1f}%  (<15% CAGR)")
    score = (med_cagr * 2) - abs(avg_dd * 0.5) - (ruin_rate * 2)
    rank = "S (GODLIKE)" if score > 80 else "A (ROBUST)" if score > 50 else "B (STABLE)" if score > 20 else "C (FRAGILE)" if score > 0 else "D (CURVE-FITTED)"
    print(f"\n  ROBUSTNESS RANK: {rank} (Score: {score:.1f})")
    print("\n" + "=" * w + "\n")
